### ISSUE TITLE
responsive navbar with "LOGO" , Search bar and search icon

### ISSUE THREAD

**Issue by DhanrajKamble** [DhanrajKamble/ThePokedex#1]
1. "Logo" should be on the left-most side.
2. In computer width, the "search bar and search icon" are on the right side.

**Comment by tran1109** [comment]
Do you need to design an interface for your website? Do you need to design an index.html page? If so, can I try it?

**Comment by DhanrajKamble** [comment]
I assigned this issue to you

**Comment by tran1109** [comment]
Hello! Can you assign me? Because I need it to demonstrate my assignment.
![assigned](https://github.com/DhanrajKamble/ThePokedex/assets/141980939/a66659f9-6c2b-4cc4-810c-ea544dc6bfdc)

**Comment by Rahufkhan** [comment]
tran1109. You can work on this issue

**Comment by tran1109** [comment]
I have submitted a pull request. I wonder if you saw it?
