### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by DhanrajKamble** [DhanrajKamble/ThePokedex#19]
**Is your feature request related to a problem? Please describe.**
Add responsiveness to the different screen sizes.

**Describe the solution you'd like**
For a mobile size    -> only one box
For a tablet size    -> only two boxes
For a larger size    -> only three boxes

**Comment by minhkha912** [comment]
Can you assign it for me?

**Comment by DhanrajKamble** [comment]
> Can you assign it for me?

of course, you can work on it.

**Comment by minhkha912** [comment]
I have done it. Please check and tell to me if you have any problems. Also, can you add 'Assignees' role for me? I need that for my homework. Thank you!
