### ISSUE TITLE
Responsive Navigation bar

### ISSUE THREAD

**Issue by DhanrajKamble** [DhanrajKamble/ThePokedex#20]
**Is your feature request related to a problem? Please describe.**
Responsive design of Navigation menu

**Describe the solution you'd like**
In mobile mode, the LOGO is on the top left, and the Search tab and search button are below the LOGO.
In tablet size and large size, the logo is on the left side, and the search tab and search button are below the logo.

**Comment by minhkha912** [comment]
Can you assign it for me?

**Comment by DhanrajKamble** [comment]
Can you assign it to me?
You can work on it, of course.
