### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by DhanrajKamble** [DhanrajKamble/ThePokedex#3]
- Footer with text "All ©copyright are reserved to ThePokedex 2023".

- It should be centered.

**Comment by Fahass** [comment]
I'd like to work on this issue.

**Comment by DhanrajKamble** [comment]
Yes you can work on it

**Comment by nguyenthihuynhgiao** [comment]
hi, can you assigned for me ?

**Comment by Rahufkhan** [comment]
Fahass you can work on it.
