### ISSUE TITLE
[feat] Create footer of the website

### ISSUE THREAD

**Issue by Rahufkhan** [DhanrajKamble/ThePokedex#43]
**Is your feature request related to a problem? Please describe.**
create footer with one logo and text provided in the screen shot.
![footer](https://github.com/DhanrajKamble/ThePokedex/assets/62764275/c3c09960-9f5d-40c2-a979-0e4a3de5081b)

**Describe the solution you'd like**
create exactly similar of what we provided in the screen shot.

**Additional context**
the logo of the footer is this you can download it attach in your code

![go-hub-logo](https://github.com/DhanrajKamble/ThePokedex/assets/62764275/444edccd-a670-421a-a1f0-45caed15582d)

**Comment by JonnyMc94** [comment]
Hey @Rahufkhan, I would like to contribute to this issue. Could you assign it to me?
