### ISSUE TITLE
[Bug]: padding issue in nav card box

### ISSUE THREAD

**Issue by Rahufkhan** [DhanrajKamble/ThePokedex#44]
### Describe the bug

Nav card have padding issue in mobile size screen. In dextop screen padding issue will not occur when Change the screen to mobile size and then click on menu bar then the card padding size issue will occurs.

### To Reproduce

1. Go to the pokedex website
2. Click on nav bar
3. Scroll down to see the passing issue on card bix.

### Expected behavior

Pat some passing on nav card in the menu bar.

![IMG-20231110-WA0002](https://github.com/DhanrajKamble/ThePokedex/assets/62764275/1b02b6c0-1cc0-4ebe-8327-b8878edf2da6)
### Screenshots/Videos

![IMG-20231110-WA0001](https://github.com/DhanrajKamble/ThePokedex/assets/62764275/a81934c5-cef0-491e-8ba4-07d44da99fe2)

### Please checkmark the following checklist

- [X] I make sure that similar issue is not opened

**Comment by JonnyMc94** [comment]
Hey @Rahufkhan , I would like to contribute to this issue. Could you assign it to me?

**Comment by JonnyMc94** [comment]
I am working on this one, PR incoming
